version: 2
updates:
  - package-ecosystem: npm
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@ariswap/token-lists"
      - dependency-name: "@ariswap/default-token-list"
